name: 🆘 Help
description: 도움이 필요하신가요?
title: '[🆘 Help] '
labels: ['🆘 Help']
body:
  - type: textarea
    id: help-description
    attributes:
      label: 📄 설명
      description: |
        도움이 필요한 부분에 대한 설명을 작성해 주세요.
      placeholder: |
        - 여기에 설명을 적어주세요
    validations:
      required: true
  - type: textarea
    id: help-checklist
    attributes:
      label: 📋 체크리스트
      description: |
        아래 체크리스트를 작성해주세요.
      placeholder: |
        - [ ] 도움 요청 사항 설명
        - [ ] 추가 정보 필요
    validations:
      required: true
  - type: textarea
    id: help-more
    attributes:
      label: 📝 메모
      description: 더 하고 싶은 말이 있다면 작성해 주세요.
    validations:
      required: false
